AWSTemplateFormatVersion: '2010-09-09'
Description: COMPLIANT - S3 bucket encrypted with a customer-managed KMS key (CMK)

Resources:
  S3Cmk:
    Type: AWS::KMS::Key
    Properties:
      Description: CMK for S3 encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccountAdmin
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  CompliantBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3Cmk
            BucketKeyEnabled: true
