AWSTemplateFormatVersion: '2010-09-09'
Description: NON-COMPLIANT - S3 bucket using SSE-S3 (AES256), no customer-managed KMS key

Resources:
  NonCompliantBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
